var listArray = [
        {
        name: 'PVCs: Approach & Management',
        description: 'How to approach and manage patients with PVCs',
        link: 'PVCs/index.html',
        thumb: 'media/PVC.png',
        date: new Date(25,9,09),
        latest: 1,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 0,
        mBasic: 1
    },
    {
        name: 'NOACs in AF with CKD',
        description: 'NOACs in AF with CKD: 2025 Update',
        link: 'noacinckd/index.html',
        thumb: 'media/noacInCKD.png',
        date: new Date(25,7,28),
        latest: 1,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 0,
        mBasic: 1
    },
    {
        name: 'EP Trials Highlights 2025',
        description: 'Important Trials on Clinical Cardiac Electrophysiology in 2025.',
        link: 'epTrials2025/index.html',
        thumb: 'media/epTrials2025.png',
        date: new Date(25,5,25),
        latest: 1,
        audFav: 1,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 0,
        mBasic: 1
    },
    {
        name: 'Cryoballoon PVI',
        description: 'Concept & Supporting Data',
        link: 'Cryo/index.html',
        thumb: 'media/cryo.gif',
        date: new Date(24,10,20),
        latest: 0,
        audFav: 1,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 0,
        mBasic: 1
    },
    {
        name: 'Basic ICD Concept: Qs & As',
        description: 'Basic functions and settings of ICD',
        link: 'BasicICDQA/index.html',
        thumb: 'media/basicICDQA.png',
        date: new Date(24,9,22),
        latest: 0,
        audFav: 1,
        authFav: 0,
        QA: 1,
        gLines: 0,
        basic: 1,
        mBasic: 0
    },
    {
        name: 'Management of AF in Acute Heart Failure',
        description: 'Cardioversion, Anticoagulation, and Rate Control',
        link: 'AFinHF/index.html',
        thumb: 'media/AFinHF.png',
        date: new Date(24,9,9),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 0,
        mBasic: 1
    },
    {
        name: 'Optimal Candidates for AF Ablation',
        description: 'The Concept of Cheery Picking',
        link: 'cherryPicking/index.html',
        thumb: 'media/cherryPicking.gif',
        date: new Date(24,2,29),
        latest: 0,
        audFav: 0,
        authFav: 1,
        QA: 0,
        gLines: 0,
        basic: 0,
        mBasic: 1
    },
    {
        name: 'Management of Reflex Syncope',
        description: 'Update in management of reflex syncope',
        link: 'syncope/reflexsyncope/index.html',
        thumb: 'media/reflexSyncope.png',
        date: new Date(23,9,9),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 1,
        mBasic: 0
    },
    {
        name: 'The Perfect Clot & How to Block It',
        description: 'NOACs Update 2023',
        link: 'perfectclot/index.html',
        thumb: 'media/perfectClot.png',
        date: new Date(23,9,9),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 1,
        mBasic: 0
    },
    {
        name: 'Basic Electrophysiology for Everyone: 2025 Update',
        description: 'Basic EP | ECG | Clinical Practice for cardiac rhythm device specialists and generial cardiologists.',
        link: 'ibhre/index.html',
        thumb: 'media/basicep.png',
        date: new Date(25,7,9),
        latest: 1,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 1,
        mBasic: 0
    },
    {
        name: 'Basic Pacing Concept: 2025 Update',
        description: 'Qs&As on Basic Pacing Concepts | Updated 2023 -- more questions added',
        link: 'basicPPM/index.html',
        thumb: 'media/basicPPM.png',
        date: new Date(25,5,9),
        latest: 1,
        audFav: 0,
        authFav: 0,
        QA: 1,
        gLines: 0,
        basic: 1,
        mBasic: 0
    },
    {
        name: '2022 ESC Guidelines for SCD & VA',
        description: 'Focus on CAD & DCM/HNDCM',
        link: 'SCD GL 2022/index.html',
        thumb: 'media/SCD GL 2022.png',
        date: new Date(22,9,1),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 1,
        basic: 0,
        mBasic: 1
    },
    {
        name: 'Catheter Ablation for AF: 2024 Update',
        description: 'Procedural Consideration',
        link: 'afAblation/index.html',
        thumb: 'media/afAblation.png',
        date: new Date(24,5,17),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 0,
        mBasic: 1
    },
    {
        name: 'Arrhythmias 2021 Update',
        description: 'ESC Guidelines on PPM/CRT, APAF-CRT, and many more.',
        link: 'Update2021/index.html',
        thumb: 'media/update2021.png',
        date: new Date(21,8,1),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 1,
        basic: 0,
        mBasic: 1
    },
    {
        name: 'EP Trials Update 2020',
        description: 'Important Trials on Clinical Cardiac Electrophysiology in 2020.',
        link: 'epUpdate/index.html',
        thumb: 'media/epUpdate.png',
        date: new Date(20,11,1),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 0,
        mBasic: 1
    },
    {
        name: 'Syncope Review',
        description: 'definitions | risk stratifications | testing | recurrency',
        link: 'Syncope/index.html',
        thumb: 'media/syncope.png',
        date: new Date(20,9,1),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 1,
        mBasic: 0
    },
    {
        name: 'Catheter Ablation for Atrial Flutter & Atrial Tachycardia: 2021 Update',
        description: 'electrophysiologic Perspectives: egm | ablation techniques | electroanatomical mapping',
        link: 'AblAA/index.html',
        thumb: 'media/ablaa.png',
        date: new Date(21,5,1),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 0,
        mBasic: 1
    },
    {
        name: 'AF Update 09.20',
        description: 'EAST-AFNET 4 Trial | 2020 ESC Guidelines',
        link: 'afUpdate/index.html',
        thumb: 'media/afUpdate.png',
        date: new Date(20,9,1),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 1,
        basic: 0,
        mBasic: 1
    },
    {
        name: 'AF Management: 10 Points to Remember',
        description: 'Things that you may forget, not realize, or not recognize yet.',
        link: 'AFMx/index.htm',
        thumb: 'media/AFMx.png',
        date: new Date(20,7,1),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 1,
        mBasic: 0
    },
    {
        name: 'Cardiac Rhythm Device Troubleshooting',
        description: 'Interesting Device related ECGs & Device Tracings',
        link: 'CRD/index.html',
        thumb: 'media/CRD.png',
        date: new Date(24,8,16),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 1,
        gLines: 0,
        basic: 0,
        mBasic: 1
    },
    {
        name: 'Sudden Cardiac Death: Myths & Facts',
        description: 'Basic Understanding of Sudden Cardiac Deaths, Common Causes, Treatments, and Prevention',
        link: 'SCD/index.html',
        thumb: 'media/SCDM&F.png',
        date: new Date(20,3,10),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 1,
        mBasic: 0
    },
    {
        name: 'Cardiac Electrophysiology Qs&As 2020s',
        description: 'Aimed for board preparation and quick knowledge update. Coming in 3 topics (for now): Basic Pacing Concepts, Sudden Cardiac Death, and Top Tracings.',
        link: 'QA2020/index.html',
        thumb: 'media/Ep QA.png',
        date: new Date(20,3,1),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 1,
        gLines: 0,
        basic: 1,
        mBasic: 0
    },
    {
        name: 'J-Wave Syndrome',
        description: 'A Brief Introduction with Latest Update on J-wave Syndrome',
        link: 'jWave/index.html',
        thumb: 'media/jWave.png',
        date: new Date(20,1,1),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 1,
        mBasic: 0
    },
    {
        name: 'Non-cardiac Causes of abnormal ECGs.',
        description: 'Abnormal ECGs from lungs & brain pathology, electrolyte abnormalites, and other metabolic derangement.',
        link: 'ECG/index.html',
        thumb: 'media/ecg.png',
        date: new Date(19,10,1),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 1,
        mBasic: 0
    },
    {
        name: 'His-Bundle Pacing ',
        description: 'Is His-Bundle Pacing preferred over CRT?: The Debate',
        link: 'HBP/index.html',
        thumb: 'media/HBP.png',
        date: new Date(19,3,1),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 0,
        mBasic: 1
    },
    {
        name: 'SCD Burden Plot',
        description: 'Original work to elaborate the burden of SCD.',
        link: 'SCD GL 2022/scdPlot_circle.html',
        thumb: 'media/scdPlot.png',
        date: new Date(22,9,1),
        latest: 0,
        audFav: 0,
        authFav: 1,
        QA: 0,
        gLines: 0,
        basic: 0,
        mBasic: 1
    },
    {
        name: 'Basic Pacing Concept VDO Clips (Thai)',
        description: 'Pacemaker Concept Simplified in 8 VDO Clips',
        link: 'https://www.youtube.com/playlist?list=PLSVT4h46-zUKFeYejS2Js3zWRrVEC_1eG',
        thumb: 'media/ppmBasicVdo.png',
        date: new Date(22,9,2),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 1,
        mBasic: 0
    },
    {
        name: 'Wide Complex Tachycardia VDO Clips (Thai)',
        description: '8 Interesting Points of Approach to Wide Complex Tachycardia',
        link: 'https://www.youtube.com/playlist?list=PLSVT4h46-zUKvPkxHWtaRUF4oJ9KEccM5',
        thumb: 'media/wctVdo.png',
        date: new Date(22,5,30),
        latest: 0,
        audFav: 0,
        authFav: 0,
        QA: 0,
        gLines: 0,
        basic: 1,
        mBasic: 0
    },
    {
        name: 'Biophysics of Ablation VDO Clips (Thai)',
        description: 'The Heat, The Freeze, The Temp, and The 3D',
        link: 'https://www.youtube.com/playlist?list=PLSVT4h46-zUJPJ_3o9fMpVpRtDtPz6f5w',
        thumb: 'media/ablPhysicsVdo.png',
        date: new Date(21,10,23),
        latest: 0,
        audFav: 0,
        authFav: 1,
        QA: 0,
        gLines: 0,
        basic: 1,
        mBasic: 0
    }

]